name: gpu-job

on:
    pull_request:
        branches:
        - '*'
    push:
        branches:
        - master
        - main
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    gpu-job:
        name: gpu-job
        runs-on: [actuated-8cpu-16gb, gpu]
        steps:
        - uses: actions/checkout@v1
        - run: |
            lspci -kk -nn
        - uses: self-actuated/connect-ssh@master

        - uses: self-actuated/nvidia-run@master
        - name: Run nvidia-smi
          run: |
            nvidia-smi -L
            nvidia-smi
